// Checks for the original 31 tools.
import { set, val, giveFile } from '../helpers.mjs';

export default {
  token: [`(${val('.output textarea')}.length === 32 ? '' : 'token length ' + ${val('.output textarea')}.length)`],
  hash: [set('textarea', 'hello'), 'new Promise(r => setTimeout(r, 300))',
    `(${val('.output input', 0)} === '5d41402abc4b2a76b9719d911017c592' && ${val('.output input', 2)} === '2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824' ? '' : 'hash wrong: ' + ${val('.output input', 0)})`],
  bcrypt: [set('input.input', 'secret', 3), set('input.input', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 4), 'new Promise(r => setTimeout(r, 1500))',
    `(document.querySelector('.verdict').textContent.includes('No match') ? '' : 'bcrypt verdict: ' + document.querySelector('.verdict').textContent)`,
    set('input.input', 'secret', 0), `document.querySelector('.btn.primary').click()`, 'new Promise(r => setTimeout(r, 1500))',
    `(() => { const i = document.querySelectorAll('input.input'); i[4].value = i[2].value; i[4].dispatchEvent(new Event('input')); })()`, 'new Promise(r => setTimeout(r, 1500))',
    `(document.querySelector('.verdict').textContent.includes('✓ Match') ? '' : 'bcrypt round trip: ' + document.querySelector('.verdict').textContent)`],
  uuid: [`(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(${val('.output textarea')}) ? '' : 'uuid v4 bad')`,
    `(document.querySelectorAll('.tabs button')[1].click(), /^[0-9a-f]{8}-[0-9a-f]{4}-7/.test(${val('.output textarea')}) ? '' : 'uuid v7 bad')`,
    `(document.querySelectorAll('.tabs button')[2].click(), /^[0-9A-HJKMNP-TV-Z]{26}$/.test(${val('.output textarea')}) ? '' : 'ulid bad ' + ${val('.output textarea')})`],
  jwt: [set('textarea', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyMzkwMjJ9.x'),
    `(${val('.output textarea', 1)}.includes('John Doe') && document.querySelector('.verdict').textContent.includes('Expired') ? '' : 'jwt decode failed')`],
  base64: [set('textarea', 'Héllo 👋', 0), `(${val('textarea', 1)} === 'SMOpbGxvIPCfkYs=' ? '' : 'b64 encode: ' + ${val('textarea', 1)})`,
    set('textarea', 'U2VsYW1hdCBwYWdp', 1), `(${val('textarea', 0)} === 'Selamat pagi' ? '' : 'b64 decode')`],
  formats: [`(${val('.output textarea')}.includes('weekday: 180') ? '' : 'json->yaml: ' + ${val('.output textarea')})`,
    `(document.querySelectorAll('select')[1].value = 'TOML', document.querySelectorAll('select')[1].dispatchEvent(new Event('change')), ${val('.output textarea')}.includes('[prices]') ? '' : 'json->toml')`,
    `(document.querySelectorAll('select')[1].value = 'CSV', document.querySelectorAll('select')[1].dispatchEvent(new Event('change')), ${val('.output textarea')}.includes('prices.weekday') ? '' : 'json->csv: ' + ${val('.output textarea')})`],
  datetime: [set('input.input', '1759800000'), `(${val('.output input', 2)} === '2025-10-07T01:20:00.000Z' ? '' : 'iso: ' + ${val('.output input', 2)})`],
  color: [set('input.input', 'rgb(232 163 61)'), `(${val('.output input', 0)} === '#e8a33d' && ${val('.output input', 2)} === 'hsl(36 79% 57%)' ? '' : 'colour: ' + ${val('.output input', 0)} + ' ' + ${val('.output input', 2)})`,
    set('input.input', 'teal'), `(${val('.output input', 0)} === '#008080' ? '' : 'named colour')`],
  bases: [`(${val('input.input', 0)} === '11111101010' && ${val('input.input', 3)} === '7ea' ? '' : 'bases: ' + ${val('input.input', 0)})`,
    set('input.input', 'ffffffffffffffffffff', 3), `(${val('input.input', 2)} === '1208925819614629174706175' ? '' : 'bigint: ' + ${val('input.input', 2)})`],
  url: [`(document.querySelectorAll('.table tr').length === 4 ? '' : 'query rows ' + document.querySelectorAll('.table tr').length)`,
    set('textarea', 'a b&c', 0), `(${val('textarea', 1)} === 'a%20b%26c' ? '' : 'url encode')`],
  regex: [`(document.querySelectorAll('pre.hl mark').length === 2 ? '' : 'regex marks ' + document.querySelectorAll('pre.hl mark').length)`],
  cron: [`(document.querySelector('.big-say').textContent.includes('09:30') && document.querySelectorAll('.runs li').length === 6 ? '' : 'cron: ' + document.querySelector('.big-say').textContent)`,
    set('input.input', '0 0 31 2 *'), `(document.querySelector('.runs').textContent.includes('Never') ? '' : 'cron never')`],
  chmod: [`(${val('.output input', 0)} === 'rwxr-xr-x' ? '' : 'chmod sym')`, set('input.input', '640', 0), `(${val('.output input', 0)} === 'rw-r-----' ? '' : 'chmod 640')`],
  diff: [`(document.querySelectorAll('pre.diffview ins').length > 0 && document.querySelectorAll('pre.diffview del').length > 0 ? '' : 'diff empty')`],
  json: [`(${val('.output textarea')}.startsWith('{\\n  "guest"') ? '' : 'json pretty')`, set('textarea', '{"a":1,}', 0), `(document.querySelector('.note.error') && !document.querySelector('.note.error').hidden ? '' : 'json error not shown')`],
  qr: [`(document.querySelector('canvas.qr').toDataURL().length > 2000 ? '' : 'qr blank')`],
  lorem: [`(${val('.output textarea')}.startsWith('Lorem ipsum dolor sit amet') ? '' : 'lorem')`],
  stats: [set('textarea', 'Satu dua tiga.\n\nEmpat lima.'), `(document.querySelector('.stat strong').textContent === '5' ? '' : 'words ' + document.querySelector('.stat strong').textContent)`],
  case: [`(${val('.output input', 0)} === 'kasih-alza-homestay-bilik-keluarga' && ${val('.output input', 1)} === 'kasihAlzaHomestayBilikKeluarga' ? '' : 'case: ' + ${val('.output input', 0)})`],
  placeholder: [`(document.querySelector('.preview svg') ? '' : 'no svg preview')`],
  strength: [set('input.input', 'Password1'), `(document.querySelector('.verdict').textContent.includes('Weak') ? '' : 'Password1 not weak: ' + document.querySelector('.verdict').textContent)`,
    set('input.input', 'tukang-kayu-lompat-pagar-77'), `(document.querySelector('.kv dd').textContent.match(/about (\\d+)/)[1] < 75 ? '' : 'passphrase over-scored: ' + document.querySelector('.kv dd').textContent)`,
    set('input.input', 'tukang-kayu-lompat-pagar-tinggi-77'), `(document.querySelector('.verdict').textContent.includes('Strong') ? '' : '5-word passphrase not strong: ' + document.querySelector('.verdict').textContent)`,
    set('input.input', 'Xq7#vLp2$Rm9!kTz'), `(document.querySelector('.verdict').textContent.includes('Strong') ? '' : 'random 16 not strong')`],
  checksum: [giveFile('input[type=file]', `new File(['hello'], 'hello.txt', { type: 'text/plain' })`), 'new Promise(r => setTimeout(r, 400))',
    `(${val('.output input', 0)} === '2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824' && ${val('.output input', 3)} === '5d41402abc4b2a76b9719d911017c592' ? '' : 'file sha256: ' + ${val('.output input', 0)})`,
    set('input.input', 'sha256: 2CF24DBA5FB0A30E26E83B2AC5B9E29E1B161E5C1FA7425E73043362938B9824', 0), `(document.querySelector('.verdict').textContent.includes('Matches the SHA-256') ? '' : 'checksum compare: ' + document.querySelector('.verdict').textContent)`],
  entities: [`(${val('textarea', 1)}.includes('&lt;b&gt;RM180&lt;/b&gt; &amp; &quot;sarapan&quot;') ? '' : 'encode: ' + ${val('textarea', 1)})`,
    set('textarea', '&lt;p&gt; &copy; &#x1F44B;', 1), `(${val('textarea', 0)} === '<p> © 👋' ? '' : 'decode: ' + ${val('textarea', 0)})`],
  markdown: ['new Promise(r => setTimeout(r, 300))', `(${val('.output textarea')}.includes('<table>') && ${val('.output textarea')}.includes('<strong>3-bedroom</strong>') ? '' : 'markdown html')`,
    `(document.querySelector('iframe.md-frame').getAttribute('sandbox') === '' ? '' : 'preview iframe is not sandboxed')`],
  subnet: [`(document.querySelector('.kv').textContent.includes('192.168.1.255') && document.querySelector('.kv').textContent.includes('Usable hosts254') ? '' : 'subnet /24: ' + document.querySelector('.kv').textContent.slice(0, 120))`,
    set('input.input', '10.20.30.40 255.255.255.252'), `(document.querySelector('.kv').textContent.includes('10.20.30.40/30') && document.querySelector('.kv').textContent.includes('Usable hosts2') ? '' : 'subnet mask form')`],
  docker: ['new Promise(r => setTimeout(r, 300))', `(() => { const y = ${val('.output textarea')}; return y.includes('container_name: n8n') && y.includes('- "5678:5678"') && y.includes('n8n_data: {}') && y.includes('restart: unless-stopped') ? '' : 'compose: ' + y; })()`,
    `(document.querySelector('.tips').textContent.includes('-d') ? '' : 'no note about -d')`,
    set('textarea', 'docker run -it --rm --network host -e "A=b c" --gpus all ubuntu bash -c "echo hi"'), `(() => { const y = ${val('.output textarea')}; return y.includes('network_mode: host') && y.includes('A=b c') && y.includes('tty: true') && y.includes('- bash') && y.includes('capabilities') ? '' : 'compose 2: ' + y; })()`],
  useragent: [`document.querySelectorAll('.chip')[1].click()`, `(document.querySelector('.kv').textContent.includes('iOS 18.5') && document.querySelector('.kv').textContent.includes('Safari 18.5') ? '' : 'ua iphone: ' + document.querySelector('.kv').textContent)`,
    `document.querySelectorAll('.chip')[3].click()`, `(document.querySelector('.kv').textContent.includes('Edge 139') && document.querySelector('.kv').textContent.includes('Windows 10 or 11') ? '' : 'ua edge: ' + document.querySelector('.kv').textContent)`,
    `document.querySelectorAll('.chip')[4].click()`, `(document.querySelector('.kv').textContent.includes('Googlebot') ? '' : 'ua bot: ' + document.querySelector('.kv').textContent)`],
  sql: ['new Promise(r => setTimeout(r, 1500))', `(${val('.output textarea')}.startsWith('SELECT\\n  b.id,') && ${val('.output textarea')}.includes('LEFT JOIN payments') ? '' : 'sql: ' + ${val('.output textarea')}.slice(0, 80))`],
  http: [set('input.input', '429'), `(document.querySelectorAll('.code-row').length === 1 && document.querySelector('.code-name').textContent === 'Too Many Requests' ? '' : 'http search')`],
  qrscan: [`document.querySelectorAll('.tabs button')[1].click()`,
    `(async () => { const q = (await import(new URL('vendor/qrcode.js', location.href))).default; const m = q(0, 'M'); m.addData('WIFI:T:WPA;S:Rumah Kita;P:abc\\\\;123;;'); m.make(); const n = m.getModuleCount(), c = document.createElement('canvas'); c.width = c.height = (n + 8) * 8; const x = c.getContext('2d'); x.fillStyle = '#fff'; x.fillRect(0, 0, c.width, c.height); x.fillStyle = '#000'; for (let r = 0; r < n; r++) for (let k = 0; k < n; k++) if (m.isDark(r, k)) x.fillRect((k + 4) * 8, (r + 4) * 8, 8, 8); const blob = await new Promise(r => c.toBlob(r)); const dt = new DataTransfer(); dt.items.add(new File([blob], 'qr.png', { type: 'image/png' })); const inp = document.querySelector('input[type=file]'); inp.files = dt.files; inp.dispatchEvent(new Event('change')); await new Promise(r => setTimeout(r, 1500)); })()`,
    `(document.querySelector('.scan-result').textContent.includes('Rumah Kita') && document.querySelector('.scan-result').textContent.includes('abc;123') ? '' : 'qr scan: ' + document.querySelector('.scan-result').textContent)`],
};
